name: Build, Push Docker Image & Deploy with Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials (stored in GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build, Tag, and Push Docker image
      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_NAME=patient
          IMAGE_TAG=${{ github.sha }}
          ECR_URI=548586340409.dkr.ecr.us-east-1.amazonaws.com/patient

          echo "Building and pushing image to $ECR_URI"

          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $ECR_URI:$IMAGE_TAG
          docker tag $IMAGE_NAME:latest $ECR_URI:latest

          docker push $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest

      # 5. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6   # pick a stable version

      # 6. Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # 7. Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # 8. Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
